import { currentStaff, publicStaff } from '@/lib/auth';
import { manageAccount } from '@/lib/accounts';
import { database, permissions } from '@/lib/clinic';
const json=(data:any,init:ResponseInit={})=>Response.json(data,{...init,headers:{'Cache-Control':'no-store'}});
const roles=['Admin','Doctor','Nurse','Receptionist'];
const kinds=['patients','appointments','consultations','prescriptions','vitals','clinics'];
const fail=(message:string,status=400)=>json({error:message},{status});
export async function GET(req:Request){try{const a=await currentStaff(req);if(!a)return fail('Please sign in.',401);if(a.must_change)return fail('Change your temporary password to continue.',403);const db=database();const all=await db.prepare('SELECT * FROM records ORDER BY created_at DESC').all<any>();const records=all.results.map(r=>({...JSON.parse(r.data),id:r.id,kind:r.kind,createdAt:r.created_at,author:r.author}));const visible=records.filter(r=>a.role!=='Receptionist'||!['consultations','prescriptions','vitals'].includes(r.kind)).map(r=>a.role==='Receptionist'&&r.kind==='patients'?{...r,diagnosis:undefined,allergies:undefined}:r);const staff=await db.prepare("SELECT email,name,role,status,department,last_login,username,must_change,password_hash IS NOT NULL AS login_ready FROM staff WHERE status!='Deleted' ORDER BY name").all();const history=a.role==='Admin'?await db.prepare('SELECT * FROM audit ORDER BY id DESC LIMIT 30').all():{results:[]};return json({actor:publicStaff(a),records:visible,users:a.role==='Admin'?staff.results:staff.results.filter((s:any)=>s.role==='Doctor').map((s:any)=>({email:s.email,name:s.name,role:s.role})),audit:history.results});}catch(e){console.error(e);return fail('Unable to load clinic records. Please try again.',503);}}
export async function POST(req:Request){try{if(req.headers.get('origin')!==new URL(req.url).origin)return fail('Invalid request origin',403);const a=await currentStaff(req);if(!a)return fail('Please sign in.',401);if(a.must_change)return fail('Change your temporary password to continue.',403);const db=database();const body=await req.json() as any;const {kind,operation='save',data={}}=body;if(!permissions[a.role]?.includes(kind))return fail('Your role cannot perform this action.',403);const now=new Date().toISOString();if(kind==='users')return manageAccount(a,operation,data,body.id);
if(!kinds.includes(kind))return fail('Unknown record type');const id=body.id||crypto.randomUUID();const existing=body.id?await db.prepare('SELECT * FROM records WHERE id=? AND kind=?').bind(id,kind).first<any>():null;if(body.id&&!existing)return fail('Record not found',404);if(['consultations','prescriptions','vitals'].includes(kind)&&existing&&a.role!=='Admin'&&existing.author!==a.email)return fail('Only the author or administrator can change this record.',403);
if(operation==='delete'){if(kind!=='patients'&&kind!=='clinics')return fail('Use record status to retain history.');if(kind==='patients'){const count=await db.prepare('SELECT COUNT(*) AS n FROM records WHERE patient_id=?').bind(id).first<any>();if(count.n)return fail('This patient has visit history. Set their status to Inactive instead.');}if(kind==='clinics'){const linked=await db.prepare("SELECT COUNT(*) AS n FROM records WHERE kind='appointments' AND json_extract(data,'$.clinicId')=?").bind(id).first<any>();if(linked.n)return fail('This clinic has appointments. Set its status to Inactive instead.');}await db.batch([db.prepare('DELETE FROM records WHERE id=? AND kind=?').bind(id,kind),db.prepare('INSERT INTO audit(actor,action,record_id,at) VALUES(?,?,?,?)').bind(a.email,`Deleted ${kind}`,id,now)]);return json({ok:true});}
const clean:Record<string,any>={};const fields:Record<string,string[]>={patients:['name','dob','gender','phone','nationalId','diagnosis','allergies','status'],clinics:['name','location','specialty','capacity','status'],appointments:['patientId','clinicId','doctor','date','time','reason','status'],consultations:['patientId','date','complaint','diagnosis','notes','plan','followUp'],prescriptions:['patientId','date','medication','dose','frequency','duration','instructions'],vitals:['patientId','date','bloodPressure','pulse','temperature','weight','height','notes']};for(const key of fields[kind])clean[key]=String(data[key]??'').trim().slice(0,5000);if(kind==='patients'&&a.role==='Receptionist'){clean.diagnosis=existing?JSON.parse(existing.data).diagnosis||'':'';clean.allergies=existing?JSON.parse(existing.data).allergies||'':'';}
if(['patients','clinics'].includes(kind)&&!clean.name)return fail('Name is required.');if(kind==='patients'){if(!['Male','Female','Other'].includes(clean.gender)||!['Active','Inactive'].includes(clean.status))return fail('Select gender and status.');if(!/^\d{4}-\d{2}-\d{2}$/.test(clean.dob)||clean.dob>now.slice(0,10)||clean.dob<'1876-01-01')return fail('Enter a valid date of birth.');}if(kind==='clinics'&&(!['Operational','Near Capacity','Inactive'].includes(clean.status)||!Number.isInteger(Number(clean.capacity))||Number(clean.capacity)<1))return fail('Enter a positive whole-number capacity and valid status.');
if(!['patients','clinics'].includes(kind)){if(!clean.patientId||!await db.prepare("SELECT id FROM records WHERE id=? AND kind='patients'").bind(clean.patientId).first())return fail('Select an existing patient.');if(!/^\d{4}-\d{2}-\d{2}$/.test(clean.date)||!Number.isFinite(Date.parse(clean.date)))return fail('Choose a valid date.');}
if(kind==='appointments'){if(!['Scheduled','Waiting','In Consultation','Completed','Cancelled'].includes(clean.status))return fail('Invalid appointment status');if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(clean.time))return fail('Choose a valid time.');if(!await db.prepare("SELECT id FROM records WHERE id=? AND kind='clinics' AND json_extract(data,'$.status')!='Inactive'").bind(clean.clinicId).first())return fail('Select an operational clinic.');if(!await db.prepare("SELECT email FROM staff WHERE email=? AND role='Doctor' AND status='Active'").bind(clean.doctor).first())return fail('Select an active doctor.');const clash=await db.prepare("SELECT id FROM records WHERE kind='appointments' AND id!=? AND json_extract(data,'$.doctor')=? AND json_extract(data,'$.date')=? AND json_extract(data,'$.time')=? AND json_extract(data,'$.status') NOT IN ('Cancelled','Completed')").bind(id,clean.doctor,clean.date,clean.time).first();if(clash&& !['Cancelled','Completed'].includes(clean.status))return fail('This doctor already has an appointment at that time.');}
if(kind==='consultations'&&!clean.diagnosis)return fail('Diagnosis is required.');if(kind==='prescriptions'&&(!clean.medication||!clean.dose||!clean.frequency||!clean.duration))return fail('Medication, dose, frequency and duration are required.');if(kind==='vitals'){if(!['bloodPressure','pulse','temperature','weight','height'].some(k=>clean[k]))return fail('Enter at least one vital measurement.');for(const k of ['pulse','temperature','weight','height'])if(clean[k]&&(!Number.isFinite(Number(clean[k]))||Number(clean[k])<=0))return fail('Vital measurements must be positive numbers.');}
await db.batch([db.prepare('INSERT INTO records(id,kind,patient_id,data,created_at,updated_at,author) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at').bind(id,kind,clean.patientId||null,JSON.stringify(clean),now,now,a.email),db.prepare('INSERT INTO audit(actor,action,record_id,at) VALUES(?,?,?,?)').bind(a.email,`${existing?'Updated':'Created'} ${kind}`,id,now)]);return json({ok:true,id});}catch(e){console.error(e);return fail('Unable to save. Your input has been kept; please retry.',503);}}
