import { ensureSysadmin } from '@/lib/bootstrap';
import { database } from '@/lib/clinic';
import {getPasswordPolicy} from '@/lib/password-policy';
import {COOKIE,currentStaff,publicStaff,newSession,digest,token,random,strong,validUsername,passwordHash,verify,sameOrigin} from '@/lib/auth';
const result=(data:any,status=200,cookie?:string)=>Response.json(data,{status,headers:{'Cache-Control':'no-store',...(cookie?{'Set-Cookie':cookie}:{})}});
export async function GET(req:Request){try{await ensureSysadmin();const staff=await currentStaff(req);return result({actor:publicStaff(staff),setup:false,passwordPolicy:await getPasswordPolicy()});}catch(e){console.error(e);return result({error:'Unable to load sign-in. Please try again.'},503);}}
export async function POST(req:Request){try{if(!sameOrigin(req))return result({error:'Invalid request origin'},403);await ensureSysadmin();const db=database();const b=await req.json() as any;const now=Date.now();
if(b.action==='logout'){const t=token(req);if(t)await db.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await digest(t)).run();return result({ok:true},200,`${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`);}
if(b.action==='change-password'){const a=await currentStaff(req);if(!a)return result({error:'Please sign in again.'},401);if(!await strong(b.password))return result({error:`Use a password of ${(await getPasswordPolicy()).minLength}–128 characters.`},400);const credentials=await db.prepare('SELECT password_hash,password_salt FROM staff WHERE email=?').bind(a.email).first<any>();if(typeof b.currentPassword!=='string'||!await verify(b.currentPassword,credentials.password_hash,credentials.password_salt))return result({error:'The current password is incorrect.'},400);const salt=random(),hash=await passwordHash(b.password,salt);await db.batch([db.prepare('UPDATE staff SET password_hash=?,password_salt=?,must_change=0 WHERE email=?').bind(hash,salt,a.email),db.prepare('DELETE FROM sessions WHERE email=?').bind(a.email),db.prepare('INSERT INTO audit(actor,action,record_id,at) VALUES(?,?,?,?)').bind(a.email,'Changed account password',a.email,new Date().toISOString())]);return result({ok:true},200,await newSession(a.email));}
if(b.action!=='login')return result({error:'Unknown action.'},400);
const username=String(b.username||'').toLowerCase().trim();const password=typeof b.password==='string'?b.password:'';if(!validUsername(username)||password.length>128)return result({error:'Incorrect username or password.'},401);
const keys=[await digest('username:'+username),await digest('ip:'+(req.headers.get('cf-connecting-ip')||'unknown'))];
for(const key of keys){await db.prepare('INSERT INTO login_attempts(key,count,expires_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires_at<? THEN 1 ELSE count+1 END,expires_at=CASE WHEN expires_at<? THEN excluded.expires_at ELSE expires_at END').bind(key,now+15*60*1000,now,now).run();const attempt=await db.prepare('SELECT count FROM login_attempts WHERE key=?').bind(key).first<any>();if(attempt.count>(key===keys[0]?10:50))return result({error:'Too many sign-in attempts. Please try again in 15 minutes.'},429);}
const staff=await db.prepare("SELECT * FROM staff WHERE username=? AND status='Active'").bind(username).first<any>();const match=await verify(password,staff?.password_hash||'0'.repeat(64),staff?.password_salt||'0'.repeat(64));if(!staff?.password_hash||!match)return result({error:'Incorrect username or password.'},401);
await db.batch([db.prepare('DELETE FROM login_attempts WHERE key=?').bind(keys[0]),db.prepare('UPDATE staff SET last_login=? WHERE email=?').bind(new Date().toISOString(),staff.email)]);return result({ok:true,mustChange:!!staff.must_change&&(await getPasswordPolicy()).requireChange},200,await newSession(staff.email));
}catch(e){console.error(e);return result({error:'Unable to complete this action. Please try again.'},503);}}
